<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Le site officiel d'Avee Mana">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/ico" href="favicon.ico">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="./libraries/css/normalize.css">
    <link rel="stylesheet" href="./libraries/css/style.css">
    <link rel="stylesheet" href="./libraries/css/effects.css">


    <title>Avee Mana | <?= isset($title) ?  $title : 'Bienvenue' ?></title>
</head>

<body>

    <!-- Barre de navigation -->
    <nav id="navBar">
        <div class="transition">
            <!-- Hamburger menu -->
            <div class="hamburger-menu">
                <input id="hambToggle" type="checkbox" />
                <label class="menuBtn" name="hambToggle" for="hambToggle">
                    <span></span>
                </label>
                <ul class="menuBox">
                    <li><a class="menuItem deco" href="index.php?route=home"><i class="fa-solid fa-house"></i>&nbsp;&nbsp;&nbsp;&nbsp;ACCUEIL</a></li>
                    <li><a class="menuItem deco" href="index.php?route=shop"><i class="fa-solid fa-bag-shopping"></i>&nbsp;&nbsp;&nbsp;&nbsp;BOUTIQUE</a></li>
                    <li><a class="menuItem deco" href="index.php?route=gallery"><i class="fa-solid fa-image"></i>&nbsp;&nbsp;&nbsp;&nbsp;GALERIE</a></li>
                    <li><a class="menuItem deco" href="index.php?route=home#events"><i class="fa-solid fa-flag"></i>&nbsp;&nbsp;&nbsp;&nbsp;EVENEMENTS</a></li>
                    <li><a class="menuItem deco" href="index.php?route=contact"><i class="fa-solid fa-message"></i>&nbsp;&nbsp;&nbsp;&nbsp;CONTACT</a></li>
                    <?php if (!isset($_SESSION['user'])) : ?>
                        <li><a class="menuItem deco" href="index.php?route=login"><i class="fa-solid fa-user"></i>&nbsp;&nbsp;&nbsp;&nbsp;SE CONNECTER</a></li>
                        <li><a class="menuItem deco" href="index.php?route=addUsers"><i class="fa-solid fa-plus"></i>&nbsp;&nbsp;&nbsp;&nbsp;CREE UN COMPTE</a></li>
                    <?php else : ?>
                        <li><a class="menuItem deco" href="index.php?route=userAccount"><i class="fa-solid fa-user"></i>&nbsp;&nbsp;&nbsp;&nbsp;MON COMPTE</a></li>
                        <li><a class="menuItem deco" href="index.php?route=disconnect"><i class="fa-solid fa-user-slash"></i>&nbsp;&nbsp;&nbsp;&nbsp;SE DECONNECTER</a></li>
                    <?php endif; ?>
                </ul>
            </div>
            <!-- Fin du Menu Hamburger -->
            <div class="symbol">&#10061;</div>
            <h1 class="banNav">A V E E &nbsp;&nbsp;&nbsp;&nbsp; M A N A</h1>
            <div class="symbol">&#10061;</div>
        </div>
        <?php if (!isset($_SESSION['user'])) : ?>
            <div class="onglets">
                <ul>
                    <li class="deco dNone"><a href="index.php?route=login">Se connecter</a></li>
                    <li class="deco dNone"><a href="index.php?route=addUsers">Créer un compte</a></li>
                </ul>
            </div>
        <?php endif; ?>
        <div class="onglets">
            <ul>
                <!-- <p class="deco caddie" title="Se déconnecter"><a href="index.php?route=disconnect"><i class="fa-solid fa-power-off animate__animated animate__rubberBand"></i></a></p> -->
                <li class="deco caddie" title="Panier d'articles"><a href="index.php?route=basketProducts" aria-label="Accedez au panier d'articles"><i class="animate__animated animate__rubberBand fa-solid fa-cart-shopping"></i></a></li>
            </ul>
        </div>
    </nav>
    <!-- Fin de la barre de navigation -->
    
    <main>
        <?php include $template ?>
    </main>
        
    <!-- Pied de page -->
    <footer id="navBot">
        <ul class="listIcons">
            <li><a href="https://linktr.ee/Aveemana" target="_blank" title="LinkTree"><i class="fa-solid fa-link"></i></a></li>
            <li><a href="https://www.youtube.com/@aveemana" target="_blank" title="Youtube"><i class="fa-brands fa-youtube"></i></a></li>
            <li><a href="https://www.facebook.com/aveemana" target="_blank" title="Facebook"><i class="fa-brands fa-facebook"></i></a></li>
            <li><a href="https://www.instagram.com/avee_mana/" target="_blank" title="Instagram"><i class="fa-brands fa-instagram"></i></a></li>
            <li><a href="https://soundcloud.com/avee-mana" target="_blank" title="SoundCloud"><i class="fa-solid fa-cloud"></i></a></li>
            <li><a href="https://aveemana.bandcamp.com/" target="_blank" title="Bandcamp"><i class="fa-brands fa-bandcamp"></i></a></li>
            <li><a href="https://open.spotify.com/artist/4x2DScjhDMpX83Xhwb1Q9L?si=tYi9L4pPTyGF1LBp6MgsKg" target="_blank" title="Spotify"><i class="fa-brands fa-spotify"></i></a></li>
        </ul>
    </footer>
    <!-- Fin du pied de page -->
    <script src="https://kit.fontawesome.com/4d9bce4b44.js" crossorigin="anonymous"></script>
    <script src="libraries/js/app.js" type="module"></script>

</body>

</html>
