<header>
    <div class="register">
        <div class="formUser formLogin">
            <div class="profile animate__animated animate__tada">
                <div class="errorContainer">
                    <?php require_once 'errors.phtml'; ?>
                    <?php require_once 'valids.phtml'; ?>
                </div>
            </div>
            <h2 class="log animate__animated animate__backInDown h2p">Se connecter à votre compte</h2>

            <form class="pText" action="index.php?route=submitFormLogin" method="POST">

                <label for="email">Entrez votre email :</label>
                <input type="email" name="email" id="email" required>

                <label for="password">Entrez votre mot de passe :</label>
                <input type="password" name="password" id="password" required>

                <input type="hidden" value="<?= $token ?>" name="shield">

                <input type="submit" value="V A L I D E R" class="registerbtn" />

            </form>
        </div>
    </div>
</header>