<header>
    <h2 class="pageTitle">BOUTIQUE</h2>
    <hr>
    <section class="formProductContainer">
        <?php if (isset($_SESSION['user']) && $_SESSION['user']['role_id'] == 2) : ?>
            <!-- AFFICHAGE FORMULAIRE D'AJOUT DE PRODUIT DANS LA BDD (ADMIN) -->
            <div class="formProduct">
                <h3 class="pText"> Vous pouvez ajouter un article dans la boutique</h3>
                <div class="profile animate__animated animate__tada">
                    <div class="errorContainer">
                        <?php require_once 'errors.phtml'; ?>
                        <?php require_once 'valids.phtml'; ?>
                    </div>
                </div>
                <form action="index.php?route=submitFormAddProduct" method="POST" enctype="multipart/form-data">

                    <label for="name">Entrez le nom du produit</label>
                    <input type="text" name="name" id="name" placeholder="Nom">

                    <label for="description">Ajoutez la description du produit</label>
                    <input type="text" name="description" id="description" placeholder="Description">

                    <label for="price">Indiquez le prix </label>
                    <input type="number" name="price" id="price" placeholder="Prix">

                    <label for="quantity_in_stock">Indiquez la quantité en stock</label>
                    <input type="number" name="quantity_in_stock" id="quantity_in_stock_1" placeholder="Quantité">

                    <label for="picture_path">Indiquez le nom du fichier de l'image. ex: cover.jpeg</label>
                    <input type="file" name="picture_path" id="picture_path">
                    <small>Taille maximale : 8mo, extensions autorisées : JPEG, JPG, PNG, HEIC, WEBP ou GIF</small>
                    <small>(Privilégier le format .webp)</small>
                    <input type="submit" value="Valider" class="formbutton" />
                </form>
            </div>
        <?php endif; ?>
    </section>
    <section class="main">
        <div class="cards">
            <?php foreach ($products as $product) : ?>
                <!-- Toutes les cartes -->
                <div class="card">
                    <div class="caseImage">
                        <img src="libraries/assets/image/<?= htmlspecialchars($product['picture_path']) ?>" alt="Image d'un produit à la vente.">
                    </div>
                    <div class="card-header">
                        <h4 class="title"><?= htmlspecialchars($product['name']) ?></h4>
                        <div class="infos">
                            <p class="price pText"><?= htmlspecialchars($product['price']) ?> €</p>
                            <p class="quantityInStock price pText"><?= htmlspecialchars($product['quantity_in_stock']) ?> en stock</p>
                        </div>
                    </div>
                    <div class="card-body">
                        <!-- <hr> -->
                        <p><?= htmlspecialchars($product['description']) ?></p>
                        <!-- <hr> -->
                    </div>
                    <form>
                        <div class="card-footer">
                            <?php if (isset($_SESSION['user']) && $_SESSION['user']['role_id'] == 2) : ?>
                                <input type="hidden" value="<?= $token ?>" name="shield">
                                <input type="hidden" value="<?= $product['id'] ?>" name="id">
                                <?php if ($product['activate'] == 1) : ?>
                                    <a href="index.php?route=changeStatusProduct&id=<?= $product['id'] ?>&action=hide" class="deleteBtn">Masquer</a>
                                <?php else : ?>
                                    <a href="index.php?route=changeStatusProduct&id=<?= $product['id'] ?>&action=show" class="deleteBtn">Démasquer</a>
                                <?php endif; ?>
                            <?php else : ?>
                                <?php if ($product['quantity_in_stock'] != 0 && $product['activate'] == 1) : ?>
                                    <!-- <a href="index.php?route=addToBasket&id=<?= $product['id'] ?>&action=add" class="addToCard">Ajouter au panier</a> -->
                                    <div class="button-container-2">
                                        <span class="mas-2">Acheter</span>
                                        <a href="index.php?route=addToBasket&id=<?= $product['id'] ?>&action=add">
                                            <button type="button">Ajouter au panier</button>
                                        </a>
                                    </div>
                                <?php else : ?>
                                    <p class="soldOut">SOLD OUT</p>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                    </form>
                </div>
                <!-- Fin de toutes les cartes -->
            <?php endforeach; ?>
        </div>
    </section>
</header>