<header class="userArea">
    <h2 class="pageTitle">MON COMPTE</h2>
    <section class="profile">
        <div class="errorContainer">
            <?php require_once 'errors.phtml'; ?>
            <?php require_once 'valids.phtml'; ?>
        </div>
        <div class="details">
            <h3 class="heading">
                <?= htmlspecialchars(ucfirst(strtolower($_SESSION['user']['firstname']))) ?>
                <?= htmlspecialchars(ucfirst(strtolower($_SESSION['user']['lastname']))) ?>
            </h3>

            <div class="location">
                <p><i class="fa-solid fa-earth-americas"></i> - <?= htmlspecialchars($_SESSION['user']['city']) ?></p>
            </div>
            <p class="pText">(Cliquez pour modifier vos informations)</p>
            <div class="infosUser">
                <div class="col-4">
                    <h4>ADRESSE POSTALE</h4>
                    <div class="infoCol-4">
                        <p><?= htmlspecialchars($_SESSION['user']['firstname']) ?></p>
                        <p><?= htmlspecialchars($_SESSION['user']['lastname']) ?></p>
                    </div>
                    <p><?= htmlspecialchars($_SESSION['user']['postcode']) ?></p>
                    <p><?= htmlspecialchars($_SESSION['user']['adress']) ?></p>

                </div>
                <div class="col-4">
                    <h4>ADRESSE MAIL</h4>
                    <p><?= htmlspecialchars($_SESSION['user']['email']) ?></p>
                </div>
                <div class="col-4">
                    <h4>TELEPHONE</h4>
                    <p><?= htmlspecialchars($_SESSION['user']['phone']) ?></p>
                </div>
                <div class="col-4">
                    <h4>Abonnement à la newletter :</h4>
                    <?php if ($_SESSION['user']['newsletter'] == 1) : ?>
                        <p>Actif</p>
                    <?php else : ?>
                        <p>Inactif</p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </section>
    <section class="updateForm" id="updateInfos" style="display:none;">
        <div class="register">
            <div class="formUser">
                <h2 class="createAcc animate__animated animate__backInDown">Modification de compte</h2>
                <h3>Veuillez remplir tous les champs</h3>
                <form class="pText" action="index.php?route=submitFormUpdateUser" method="POST">
                    <label for="lastName">Entrez votre nom</label>
                    <input type="text" name="lastname" id="lastname" required value="<?= isset($_SESSION['user']['lastname']) ? htmlspecialchars($_SESSION['user']['lastname']) : '' ?>">

                    <label for="firstName">Entrez votre prénom</label>
                    <input type="text" name="firstname" id="firstname" required value="<?= isset($_SESSION['user']['firstname']) ? htmlspecialchars($_SESSION['user']['firstname']) : '' ?>">

                    <label for="password">Choisissez un mot de passe</label>
                    <br><small>(8 caractères min / 1 majuscule - 1 minuscule - 1 chiffre)</small>
                    <input type="password" name="password" id="password_1">

                    <label for="password_verify">Confirmez le mot de passe choisi</label>
                    <input type="password" name="password_confirme" id="password_2">

                    <label for="phone">Entrez votre numero de téléphone</label>
                    <input type="tel" name="phone" id="phone" value="<?= isset($_SESSION['user']['phone']) ? htmlspecialchars($_SESSION['user']['phone']) : '' ?>">

                    <label for="adress">Entrez votre adresse</label>
                    <input type="text" name="adress" id="adress" value="<?= isset($_SESSION['user']['adress']) ? htmlspecialchars($_SESSION['user']['adress']) : '' ?>">

                    <label for="postcode">Entrez votre code postal</label>
                    <input type="text" name="postcode" id="postcode" value="<?= isset($_SESSION['user']['postcode']) ? htmlspecialchars($_SESSION['user']['postcode']) : '' ?>">

                    <label for="city">Entrez le nom de votre ville</label>
                    <input type="text" name="city" id="city" value="<?= isset($_SESSION['user']['city']) ? htmlspecialchars($_SESSION['user']['city']) : '' ?>">
                    <p>Voulez vous être abonné a la newsletter?</p>
                    <div>
                        <input type="radio" name="newsletter" value="yes" id="newsletter1">
                        <label for="newsletter1">
                            Oui
                        </label>
                    </div>
                    <div>
                        <input type="radio" name="newsletter" value="no" id="newsletter2" checked>
                        <label for="newsletter2">
                            Non
                        </label>
                    </div>
                    <input type="hidden" value="<?= $token ?>" name="shield">
                    <input type="submit" value="Valider" class="registerbtn" aria-label="Valider le formulaire">
                </form>
            </div>
        </div>
    </section>
    <?php if (isset($_SESSION['user']) && $_SESSION['user']['role_id'] == 1 && count($orderViewData) > 0) : ?>
        <section class="orderTable">
            <h2 class="pText">Mes commandes</h2>
            <div class="table-wrapper">
                <table class="fl-table">
                    <thead>
                        <tr>
                            <th colspan="1">N° de Commande</th>
                            <th colspan="1">Date de la commande</th>
                            <th colspan="1">Prix total</th>
                            <th colspan="1">Statut</th>
                            <th colspan="1">Détails de la commande</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($orderViewData as $orderData) : ?>
                            <?php $order = $orderData['order']; ?>
                            <tr>
                                <td><?= htmlspecialchars($order['id']) ?></td>
                                <td><?= htmlspecialchars($order['orderDate']) ?></td>
                                <td><?= htmlspecialchars($order['totalPrice']) ?></td>
                                <td><?= htmlspecialchars($order['statusName']) ?></td>
                                <td>
                                    <?php foreach ($orderData['products'] as $product) : ?>
                                        <p><strong>Nom du produit:</strong> <?= htmlspecialchars($product['name']) ?></p>
                                        <p><strong>Quantité:</strong> <?= htmlspecialchars($order['quantity']) ?></p>
                                        <?php if (stripos($product['name'], 't-shirt') !== false && isset($_SESSION['size']) && $_SESSION['size'] != '') : ?>
                                            <p><strong>Taille:</strong> <?= htmlspecialchars($order['size']) ?></p>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </section>
    <?php endif; ?>


    <?php if (isset($_SESSION['user']) && $_SESSION['user']['role_id'] == 2) : ?>
        <hr>
        <section class="orderTable">
            <h2 class="pText">Tableau récapitulatif des commandes utilisateurs</h2>
            <div class="table-wrapper">
                <table class="fl-table">
                    <thead>
                        <tr>
                            <th colspan="1">N° de Commande</th>
                            <th colspan="1">Date de la commande</th>
                            <th colspan="1">Prix total</th>
                            <th colspan="1">Statut</th>
                            <th colspan="1">Détails de la commande</th>
                            <th colspan="1">Informations client</th>
                            <th colspan="1">Supprimer la commande</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($orderViewData as $orderData) : ?>
                            <?php $order = $orderData['order']; ?>
                            <tr>
                                <td><?= htmlspecialchars($order['id']) ?></td>
                                <td><?= htmlspecialchars($order['orderDate']) ?></td>
                                <td><?= htmlspecialchars($order['totalPrice']) ?></td>
                                <td><?= htmlspecialchars($order['statusName']) ?></td>
                                <td>
                                    <?php foreach ($orderData['products'] as $product) : ?>
                                        <p><strong>Article:</strong> <?= htmlspecialchars($product['name']) ?></p>
                                        <p><strong>Quantité:</strong> <?= htmlspecialchars($order['quantity']) ?></p>
                                        <p><strong>Prix unitaire:</strong> <?= htmlspecialchars($product['price']) ?></p>
                                        <?php if (stripos($product['name'], 't-shirt') !== false && isset($_SESSION['size']) && $_SESSION['size'] != '') : ?>
                                            <p><strong>Taille:</strong> <?= htmlspecialchars($order['size']) ?></p>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </td>
                                <td>
                                    <p><strong>Client:</strong> <?= htmlspecialchars(ucfirst($order['firstname']) . ' ' . ucfirst($order['lastname'])) ?></p>
                                    <p><strong>Adresse:</strong> <?= htmlspecialchars($order['adress']) ?></p>
                                    <p><strong>Code Postal:</strong> <?= htmlspecialchars($order['postcode']) ?></p>
                                    <p><strong>Ville:</strong> <?= htmlspecialchars($order['city']) ?></p>
                                    <p><strong>Téléphone:</strong> <?= htmlspecialchars($order['phone']) ?></p>
                                </td>
                                <td class="delete-container">
                                    <form class="form-delete-order" method="post" action="index.php?route=deleteOrder">
                                        <input type="hidden" name="orderId" value="<?= htmlspecialchars($order['id']) ?>">
                                        <button type="submit" class="btn-delete" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cette commande ?')">Suppr.</button>
                                    </form>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </section>
    <?php endif; ?>


</header>